### PR TITLE
Update all NuGet binaries to release-5.8.x for DotDevelop

### PR DESCRIPTION
**Pull request by hwthomas**
Add a README.md file and a Version marker text file

### CODE REVIEW

**Comment by hwthomas** [comment]
In preparation for a new (pending) Pull Request in https://github.com/dotdevelop/dotdevelop, the NuGet dlls in this repo need to be updated to release-5.8.  

**Option 1**
As things stand, with this repo being a submodule in https://github.com/dotdevelop/dotdevelop, this PR would need merging so the updated dlls get pulled down when `git submodule update --init --recursive` is issued during the make.  

**Option 2**
However, since MonoDevelop was archived there have been no commits to this repo since 1-Dec-2018, and there seems to be no reason to continue keeping the `nuget-binary` folder as a submodule of DotDevelop.  

The advantage of changing it to a standard folder would then allow any changes to its contents - for example, updates to later releases of NuGet.Client (https://github.com/nuget/nuget.client) to handle `.net6.0`  - to be under the single version control of the main  DotDevelop repo 

The NuGet dlls would be retained in the `main/external/nuget-binary` folder to minimise changes to the rest of the DotDevelop repo, and also to allow checking out of earlier versions of DotDevelop (when these were in the old submodule structure).  

The second option can be handled very simply by `git submodule deinit main/external/nuget-binary` in DotDevelop, and would be my preference (and the changes in this repo then become unnecessary).  

@lytico what are your thoughts?

**Comment by hwthomas** [comment]
@lytico In order to submit DotDevelop PR#91, I've pressed ahead with **Option 2**, partly because it doesn't require simultaneously accepting commits in this as well as the DotDevelop repos.

**Comment by lytico** [comment]
@hwthomas why not option 1 and:
a) create branch "dotdevelop" in https://github.com/dotdevelop/nuget-binary/ to hold it stable for dotdevelop
b) update branch "dotdevelop" to some of the more recent forks / branches, eg. yours: https://github.com/hwthomas/nuget-binary/tree/nuget-5.8

**Comment by lytico** [comment]
i made a new branch "dotdevelop" & merged this pr to it
so, in dotdevelop, you can use it if you want

**Comment by hwthomas** [comment]
@lytico Thanks for creating the `dotdevelop` branch and merging the `nuget-5.8` changes into it.  However, doesn't this option *still* require merging commits simultaneously in both repos if an update to `nuget-binary` dlls is required?  

That seems to require more work by the maintainer!  Or am I missing something?

**Comment by lytico** [comment]
@hwthomas yes, you are right. It require more work by the maintainer.
the only advantage would be that others can use a modernized nuget-binary too.

**Comment by hwthomas** [comment]
@lytico in that case, I think I'll stick with Option 2, but I'ill undertake to keep this repo (branch dotdevelop) updated when/if there are any changes.

**Pull request merged**
